// Banco de perguntas do Quiz. NÃO abra se você for jogar! 🤫
window.QUIZ_PUZZLES = {
  "2026-06-17": {
    titulo: "Quiz do dia",
    perguntas: [
      { categoria:"Em alta", pergunta:"A final da Copa do Mundo de 2026, marcada para 19 de julho, será disputada em qual estádio?", opcoes:["SoFi Stadium, em Los Angeles","MetLife Stadium, em Nova Jersey","AT&T Stadium, em Dallas","Mercedes-Benz Stadium, em Atlanta"], correta:1, explicacao:"A FIFA definiu o MetLife Stadium, em East Rutherford (Nova Jersey), como palco da final da Copa de 2026.", fonte:"Wikipédia — Final da Copa do Mundo FIFA de 2026", fonteUrl:"https://pt.wikipedia.org/wiki/Final_da_Copa_do_Mundo_FIFA_de_2026" },
      { categoria:"Em alta", pergunta:"Qual equipe conquistou o título da NBA na temporada 2025–26, vencendo as finais em junho de 2026?", opcoes:["New York Knicks","Boston Celtics","San Antonio Spurs","Oklahoma City Thunder"], correta:0, explicacao:"O New York Knicks venceu o San Antonio Spurs por 4 a 1 e conquistou o título da NBA, com Jalen Brunson eleito MVP das finais.", fonte:"NBA.com — Jalen Brunson 2026 Finals MVP", fonteUrl:"https://www.nba.com/news/jalen-brunson-wins-bill-russell-trophy-as-2026-nba-finals-mvp" },
      { categoria:"Em alta", pergunta:"Os Jogos Olímpicos de Inverno de 2026, realizados em fevereiro, tiveram a Itália como sede. Quais cidades dão nome ao evento?", opcoes:["Turim e Cortina","Roma e Milão","Milão e Cortina d'Ampezzo","Veneza e Bolzano"], correta:2, explicacao:"A edição foi oficialmente batizada de Milão-Cortina 2026, co-sediada por Milão e Cortina d'Ampezzo, no norte da Itália.", fonte:"Olympics.com — Milano Cortina 2026", fonteUrl:"https://www.olympics.com/en/olympic-games/milano-cortina-2026" },
      { categoria:"Lógica", pergunta:"Maria é mais velha que João, e João é mais velho que Ana. Quem é necessariamente a mais nova dos três?", opcoes:["Maria","João","Ana","Não dá para saber"], correta:2, explicacao:"Como Maria > João > Ana em idade, Ana é necessariamente a mais nova.", fonte:"", fonteUrl:"" },
      { categoria:"Lógica", pergunta:"Quantos minutos faltam para as 6h se agora são 4h45?", opcoes:["75 minutos","90 minutos","60 minutos","45 minutos"], correta:0, explicacao:"De 4h45 até 5h00 são 15 minutos, mais 60 minutos até 6h00, totalizando 75 minutos.", fonte:"", fonteUrl:"" },
      { categoria:"Lógica", pergunta:"Complete a sequência: 1, 1, 2, 3, 5, 8, ?", opcoes:["11","12","13","15"], correta:2, explicacao:"É a sequência de Fibonacci: cada número é a soma dos dois anteriores, então 5 + 8 = 13.", fonte:"", fonteUrl:"" },
      { categoria:"Conhecimentos gerais", pergunta:"Qual é a capital da Austrália?", opcoes:["Sydney","Melbourne","Camberra","Brisbane"], correta:2, explicacao:"A capital da Austrália é Camberra, planejada para evitar a rivalidade entre Sydney e Melbourne.", fonte:"Wikipédia — Camberra", fonteUrl:"https://pt.wikipedia.org/wiki/Camberra" },
      { categoria:"Conhecimentos gerais", pergunta:"Qual é o gás mais abundante na atmosfera terrestre?", opcoes:["Oxigênio","Nitrogênio","Dióxido de carbono","Argônio"], correta:1, explicacao:"O nitrogênio compõe cerca de 78% da atmosfera, bem mais que o oxigênio (cerca de 21%).", fonte:"Wikipédia — Atmosfera da Terra", fonteUrl:"https://pt.wikipedia.org/wiki/Atmosfera_da_Terra" },
      { categoria:"Conhecimentos gerais", pergunta:"Quem escreveu a peça 'Romeu e Julieta'?", opcoes:["William Shakespeare","Molière","Oscar Wilde","Anton Tchekhov"], correta:0, explicacao:"'Romeu e Julieta' foi escrita por William Shakespeare por volta do fim do século XVI.", fonte:"Wikipédia — Romeu e Julieta", fonteUrl:"https://pt.wikipedia.org/wiki/Romeu_e_Julieta" },
      { categoria:"Conhecimentos gerais", pergunta:"Qual é o menor país do mundo em área territorial?", opcoes:["Mônaco","Nauru","Vaticano","San Marino"], correta:2, explicacao:"O Vaticano é o menor país do mundo, com cerca de 0,44 km² de área.", fonte:"Wikipédia — Vaticano", fonteUrl:"https://pt.wikipedia.org/wiki/Vaticano" }
    ]
  },
  "2026-06-18": {
    titulo: "Quiz do dia",
    perguntas: [
      { categoria:"Em alta", pergunta:"Qual time conquistou a Stanley Cup de 2026, encerrando o jejum de duas décadas ao vencer as finais em junho de 2026?", opcoes:["Vegas Golden Knights","Carolina Hurricanes","Edmonton Oilers","Florida Panthers"], correta:1, explicacao:"O Carolina Hurricanes venceu o Vegas Golden Knights e conquistou a Stanley Cup pela primeira vez desde 2006.", fonte:"NHL.com — Carolina Hurricanes Win 2026 Stanley Cup Final", fonteUrl:"https://www.nhl.com/hurricanes/news/carolina-hurricanes-win-2026-stanley-cup-final" },
      { categoria:"Em alta", pergunta:"Qual país liderou o quadro geral de medalhas dos Jogos Olímpicos de Inverno de 2026, com recorde de ouros?", opcoes:["Estados Unidos","Alemanha","Noruega","Canadá"], correta:2, explicacao:"A Noruega liderou o quadro com 18 medalhas de ouro, recorde para uma única nação em Jogos de Inverno.", fonte:"NBC Olympics — Final medal count 2026 Milan Cortina", fonteUrl:"https://www.nbcolympics.com/news/final-medal-count-2026-milan-cortina-winter-olympics-and-paralympics" },
      { categoria:"Em alta", pergunta:"O Centro Presidencial Barack Obama, com museu e biblioteca, abriu ao público em junho de 2026. Em qual cidade ele fica?", opcoes:["Washington, D.C.","Honolulu","Chicago","Nova York"], correta:2, explicacao:"O Obama Presidential Center fica no Jackson Park, em Chicago, e abriu ao público em 19 de junho de 2026.", fonte:"Obama Foundation — Grand Opening", fonteUrl:"https://www.obama.org/visit/grand-opening/faq/" },
      { categoria:"Lógica", pergunta:"Um pai tem 40 anos e o filho tem 10. Daqui a quantos anos o pai terá exatamente o dobro da idade do filho?", opcoes:["10 anos","15 anos","20 anos","30 anos"], correta:2, explicacao:"Em x anos: 40 + x = 2 × (10 + x); resolvendo, 40 + x = 20 + 2x, logo x = 20 anos.", fonte:"", fonteUrl:"" },
      { categoria:"Lógica", pergunta:"Se 3 gatos caçam 3 ratos em 3 minutos, quantos gatos são necessários para caçar 100 ratos em 100 minutos?", opcoes:["100 gatos","33 gatos","3 gatos","10 gatos"], correta:2, explicacao:"Cada gato caça 1 rato a cada 3 minutos, então em 100 minutos 3 gatos caçam cerca de 100 ratos: bastam 3 gatos.", fonte:"", fonteUrl:"" },
      { categoria:"Lógica", pergunta:"Em uma corrida, você ultrapassa o corredor que está em segundo lugar. Em qual posição você fica?", opcoes:["Primeiro","Segundo","Terceiro","Depende dos demais"], correta:1, explicacao:"Ao ultrapassar o segundo colocado, você toma o lugar dele e passa a ocupar a segunda posição, não a primeira.", fonte:"", fonteUrl:"" },
      { categoria:"Conhecimentos gerais", pergunta:"Em que continente fica o deserto do Saara?", opcoes:["Ásia","África","Oceania","América do Sul"], correta:1, explicacao:"O Saara é o maior deserto quente do mundo e está localizado no norte da África.", fonte:"Wikipédia — Deserto do Saara", fonteUrl:"https://pt.wikipedia.org/wiki/Deserto_do_Saara" },
      { categoria:"Conhecimentos gerais", pergunta:"Quem desenvolveu a teoria da relatividade?", opcoes:["Isaac Newton","Niels Bohr","Albert Einstein","Galileu Galilei"], correta:2, explicacao:"Albert Einstein formulou as teorias da relatividade restrita (1905) e geral (1915).", fonte:"Wikipédia — Albert Einstein", fonteUrl:"https://pt.wikipedia.org/wiki/Albert_Einstein" },
      { categoria:"Conhecimentos gerais", pergunta:"Qual é o oceano mais profundo do planeta?", opcoes:["Atlântico","Índico","Ártico","Pacífico"], correta:3, explicacao:"O Oceano Pacífico é o mais profundo, abrigando a Fossa das Marianas, ponto mais fundo dos oceanos.", fonte:"Wikipédia — Oceano Pacífico", fonteUrl:"https://pt.wikipedia.org/wiki/Oceano_Pac%C3%ADfico" },
      { categoria:"Conhecimentos gerais", pergunta:"Quantos lados tem um hexágono?", opcoes:["5","6","7","8"], correta:1, explicacao:"Um hexágono é um polígono de seis lados e seis ângulos.", fonte:"Wikipédia — Hexágono", fonteUrl:"https://pt.wikipedia.org/wiki/Hex%C3%A1gono" }
    ]
  }
};
